//! Maintainer-only tool that regenerates the vendored prost output under
//! `src/proto/generated/` from the `.proto` files in `proto/`.
//!
//! Run from the repository root with:
//!
//! ```bash
//! cargo run --manifest-path tools/gen-proto/Cargo.toml
//! ```
//!
//! CI enforces that the committed output matches the result of running this
//! tool (see `.github/workflows/ci.yml`).

use std::fs;
use std::path::{Path, PathBuf};

// Inner attributes (`#![...]`) cannot appear inside an `include!` expansion,
// so this header is restricted to comments. Module-level attributes such as
// `#[rustfmt::skip]` and `#[allow(clippy::all)]` are applied to the wrapping
// `pub mod sketchlib { ... }` in `src/proto.rs` instead.
const HEADER: &str = "\
// @generated by tools/gen-proto -- DO NOT EDIT.
//
// Regenerate with:
//     cargo run --manifest-path tools/gen-proto/Cargo.toml
//
// Source of truth: proto/**/*.proto
";

const PROTO_FILES: &[&str] = &[
    "common/common.proto",
    "countminsketch/countminsketch.proto",
    "countsketch/countsketch.proto",
    "hll/hll.proto",
    "kll/kll.proto",
    "ddsketch/ddsketch.proto",
    "univmon/univmon.proto",
    "hydra/hydra.proto",
    "cocosketch/cocosketch.proto",
    "elasticsketch/elasticsketch.proto",
    "sketchlib.proto",
];

fn main() {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let repo_root = manifest_dir
        .parent()
        .and_then(Path::parent)
        .expect("tools/gen-proto must live two levels below the repo root");

    let proto_dir = repo_root.join("proto");
    let out_dir = repo_root.join("src/proto/generated");

    fs::create_dir_all(&out_dir).expect("failed to create generated proto directory");

    let protoc =
        protoc_bin_vendored::protoc_bin_path().expect("failed to locate vendored protoc binary");
    // SAFETY: single-threaded maintainer tool; setting PROTOC before invoking
    // prost-build is the documented way to override the protoc binary.
    unsafe {
        std::env::set_var("PROTOC", protoc);
    }

    let protos: Vec<PathBuf> = PROTO_FILES.iter().map(|p| proto_dir.join(p)).collect();

    prost_build::Config::new()
        .out_dir(&out_dir)
        .compile_protos(&protos, &[proto_dir.clone()])
        .expect("prost_build failed to compile proto files");

    prepend_header_to_generated(&out_dir);

    eprintln!("Generated proto code under {}", out_dir.display());
}

fn prepend_header_to_generated(out_dir: &Path) {
    for entry in fs::read_dir(out_dir).expect("failed to read generated directory") {
        let entry = entry.expect("failed to iterate generated directory");
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("rs") {
            continue;
        }
        let body = fs::read_to_string(&path)
            .unwrap_or_else(|err| panic!("failed to read {}: {err}", path.display()));
        if body.starts_with(HEADER) {
            continue;
        }
        let mut with_header = String::with_capacity(HEADER.len() + body.len() + 1);
        with_header.push_str(HEADER);
        with_header.push('\n');
        with_header.push_str(&body);
        fs::write(&path, with_header)
            .unwrap_or_else(|err| panic!("failed to write {}: {err}", path.display()));
    }
}
