// Proto-generated types for cross-language sketch serialization.
// Generated by prost-build from proto/sketchlib.proto at build time.
#[allow(rustdoc::broken_intra_doc_links)]
pub mod sketchlib {
    include!(concat!(env!("OUT_DIR"), "/sketchlib.v1.rs"));
}
