// Proto-generated types for cross-language sketch serialization.
// Generated by prost-build from proto/sketchlib.proto at build time.
pub mod sketchlib {
    include!(concat!(env!("OUT_DIR"), "/sketchlib.v1.rs"));
}
