name: Rust CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**/*.md"
      - "docs/**"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "**/*.md"
      - "docs/**"

jobs:
  test:
    name: Cargo Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install protobuf compiler
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo dependencies and build artifacts
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test --all-features --verbose

      - name: Check Format
        run: cargo fmt -- --check

      - name: Check Documentation
        env:
          RUSTDOCFLAGS: "-D warnings"
        run: cargo doc --no-deps --all-features
